language: ruby
rvm:
  - 1.8.7
  - 2.0.0
notifications:
  email:
    - sbrimhall@mirantis.com
  slack:
    rooms:
      - miracloud:qPdiQJMHmCsxhpR6QTT4yr98#puppet-notify

env:
  - PUPPET_VERSION=3.7.5

after_success: "curl -m 90 198.11.213.41:9292/deploy/module/sudo"
